# Stub de config: valores con los que arrancan las pruebas. Se re-escriben
# con monkeypatch.setattr(config, "X", v) cuando hace falta variarlos.
AUDIO_INPUT_DEVICE = ""
AUDIO_SAMPLE_RATE = 48000
AUDIO_HIGHPASS_HZ = 60.0
AUDIO_TARGET_DBFS = -16.0
VAD_AGGRESSIVENESS = 2
VAD_SILENCE_TIMEOUT = 1.2
VAD_ENERGY_FACTOR = 2.0
WAKE_MAX_UTTERANCE = 4.0
LISTEN_MAX_SECONDS = 20.0
WHISPER_MODEL = "tiny"
WHISPER_INTERRUPT_MODEL = ""
WHISPER_INTERRUPT_THREADS = 2
WHISPER_INTERRUPT_BEAM_SIZE = 1
WHISPER_OFFLINE = True
WHISPER_BEAM_SIZE = 5

ELEVENLABS_API_KEY = ""
ELEVENLABS_VOICE_ID = ""
ELEVENLABS_MODEL_ID = "eleven_multilingual_v2"
TTS_DRY_RUN = False
AUDIO_LEAD_SILENCE = 0.0
TTS_NORMALIZE = True
TTS_GAIN_DB = 3.0

VISION_CAMERA_INDEX = 0
VISION_MIN_DISTANCE = 0.8
VISION_MAX_SPEED = 60
VISION_APPROACH = False
GESTURE67_ENABLED = False

ARDUINO_PORT = "/dev/ttyACM0"
ARDUINO_BAUD = 115200

VOICE_INTERRUPT_ENABLED = True
INTERRUPT_MAX_UTTERANCE = 2.0
INTERRUPT_SILENCE_TIMEOUT = 0.6
INTERRUPT_ENERGY_FACTOR = 4.0
INTERRUPT_MIN_CLIP = 0.4

TRANSLATOR_ENABLED = False
TRIVIA_ENABLED = False


def assert_required():
    return None